### ISSUE TITLE
From mailing list to GitHub issues

### ISSUE THREAD

**Issue by arekbulski** [arekbulski/python-ideas#1]
This is a continuation of the same thread on the mailing list. Please contribute to it, for everyone to see that GitHub works as well as advertised.

**Comment by phdru** [comment]
# Email vs web interfaces

The advantages of email:

* Push technology: it's delivered to my mailbox and I don't need to
  visit the discussion site.
* I can filter incoming messages and deliver them to whatever mailboxes
  I prefer.
* I can read it in any interface I prefer -- there are mail user agents
  with Web, GUI, TUI and command line interfaces.
* I can filter and sort message in whatever order I prefer -- by
  discussion, by subtopic, by date, by author.
* I can download the entire mail archive or its part to process it
  offline -- read it, search through it, write messages while offline
  to send them later.
* I can edit messages in my preferred editor (browsers with extensions
  also allow that though I consider that less convenient).
* I can pipe messages through different programs -- pagers,
  encryptors/decryptors, decoders, antispam filters.
* I have to invest some time into my tools (some people consider that a
  major disadvantage of email) but than I can use these tools for every
  mailing list in the world.

The disadvantages of email:

* One has to invest time and brainpower to learn and configure the
  tools.
* People who learned only the technical part constantly break
  netiquette rules: top-posting, overquoting, replying to digests,
  replying to unrelated thread instead of starting a new thread,
  breaking thread by not replying to correct message.
* In long discussions threads can stray far and wide.
* Plain text, no support for rich text; HTML is at most tolerated, and is
  ignored when not forbidden.

The advantages of web trackers/forums/chats:

* Everyone now has a browser and knows how to use it.
* Markup (wiki syntax, HTML, reST or Markdown) with colors, fonts, images,
  links and language-dependent syntax highlighting.
* Integrated trackers are that - integrated. One can use concise wiki syntax
  to link between code, discussions (issues and code reviews) and
  documentation (wiki pages).
* They send email notification, and some of them allow to reply or even
  to create new topics over email.
* Single thread of discussion.
* A moderator can move a discussion or its subpart to a different topic
  while in a mailing list that requires cooperation from all
  participants.

The disadvantages of web interfaces:

* They force me to always be online.
* Very limited support for themes in the interface -- I can only read
  messages in whatever web interface the servers and the browsers give
  me.
* Very limited functionality for message filtering, sorting and searching.
  Very limited support for discussion threads.
* I have to adapt to every new web interface they give me. Including
  changes in the web interfaces to which I'm already accustomed. One
  site uses Markdown with proprietary extensions, another uses limited
  subset of HTML, web forums settle with BBCodes, and every site uses
  its own emoticons.

**Comment by arekbulski** [comment]
To prove how well formatted the e-mail copy is, I attach a screenshot from
my phone. Also a screenshot of the mobile webpage for the thread. This
leads me to the point being: images are first class citizens here.

**Comment by phdru** [comment]
@arekbulski Wrong Markdown formatting, no images! :laughing: Proves one of my points — for every web interface you have to learn different markup language. :smiling_imp:

**Comment by arekbulski** [comment]
Yeah, because I am attaching from the phone. If I had a laptop at hand, there would be no problem. I will take the newlines up with the github support.

**Comment by encukou** [comment]
Your post also illustrates how editing works on Github.

* post authors (*or* repository owners) can edit posts
* the previous content is not available through the UI (or at least the way to view it is not obvious)
* e-mail notifications are not sent about edits

So, after an edit, people who use e-mail will see a different post than those who use the Web interface.

**Comment by arekbulski** [comment]
I asked the support about newlines, replying with images attached, edit notifications, and creating threads by e-mail. More updates when I get them.

**Comment by arekbulski** [comment]
Another advantage mentioned by someone already: syntax highlighting

```python
x, y = 0, 1
for i in range(n):
    x, y = y, x+y
```

**Comment by encukou** [comment]
> Quotes can be used to preserve original text, if needed.

For the record, this was also an edit (that I got no notification about). The fact that you marked one addition with "Edit:" and the other not makes this pretty confusing.

Also related to notifications: When I keep a discussion page open, Github adds new posts dynamically, but doesn't do that for edits. So, people can see even more different in-between states of the conversation than the web version and the mail version.

>>   the previous content is not available through the UI (or at least the way to view it is not obvious)
>
>Edit: You might see it this way, a thread is like an article in a printed issue. You do not want a history of individual changes but the newest most pristine version. If someone withdraws what thay said, is that a bad thing? If they did, it wasnt worth posting in the first place.

That might make more sense for software issues, but I'm not sold on this being good for discussions.

If I see a reply that does not make sense any more, I *do*  want to see what it originally replied to.

**Comment by arekbulski** [comment]
Fair points. I will put up with the support to include edit notifications. I would like those too.

**Comment by arekbulski** [comment]
Reply from GitHub support:

Since we don't publicly share our roadmap of features or releases, so we can't make any promises for implementing anything immediately or later down the road. It isn't currently possible to create new issues via email, but you may be interested in using the GitHub API:

https://developer.github.com/v3/

Specifically, our Issues API:

https://developer.github.com/v3/issues

You could use this endpoint for creating an issue through the GitHub API:

https://developer.github.com/v3/issues/#create-an-issue

From there, you can build an application that leverages this endpoint to your organization's needs.

Regarding the other feature requests that you mentioned and we've added each of your ideas there so the respective teams working on those parts of GitHub can see it.

**Comment by arekbulski** [comment]
Short version: we can make our mailing list to interface with Issues or make a phone app that will work with it (offline).
